# Generated by Django 2.0.4 on 2018-05-02 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapperBenchRam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1000)),
                ('url', models.URLField(blank=True, max_length=1000)),
                ('speed_read', models.IntegerField(blank=True)),
                ('speed_write', models.IntegerField(blank=True)),
                ('latency', models.IntegerField(blank=True)),
                ('in_stock', models.BooleanField(default=False)),
            ],
        ),
    ]
