# Generated by Django 2.0.4 on 2018-05-02 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vergleich', '0004_scrapperbenchvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapperbenchram',
            name='price',
            field=models.FloatField(blank=True, default=-1),
        ),
    ]
