# Generated by Django 2.0.4 on 2018-05-06 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vergleich', '0005_scrapperbenchram_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputerConf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vergleich.ScrapperBenchCPU', verbose_name='ЦП')),
                ('hdd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vergleich.ScrapperBenchHDD', verbose_name='ЖД')),
                ('ram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vergleich.ScrapperBenchRam', verbose_name='ОП')),
                ('vga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vergleich.ScrapperBenchVideo', verbose_name='ВУ')),
            ],
        ),
    ]
